=== filippobosi/XmlBlackBox/functional-test/src/test/resources/xmlblackbox_1_0.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xmlblackbox="http://www.xmlblackbox.org/xsd/" elementFormDefault="qualified" targetNamespace="http://www.xmlblackbox.org/xsd/" xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="TEST">
	<xs:annotation>
		<xs:documentation>
			Identify the main tag
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="VALIDATE-XML" type="xmlblackbox:VALIDATE-XML" minOccurs="0"/>
		<xs:element name="DB-CONNECTION" type="xmlblackbox:DB-CONNECTION" minOccurs="0"/>
		<xs:element name="SET-VARIABLE" type="xmlblackbox:SET-VARIABLE" minOccurs="0"/>
		<xs:element name="EXECUTE-QUERY" type="xmlblackbox:EXECUTE-QUERY" minOccurs="0"/>
		<xs:element name="CHECK-DB" type="xmlblackbox:CHECK-DB" minOccurs="0"/>
		<xs:element name="RUN-PLUGIN" type="xmlblackbox:RUN-PLUGIN" minOccurs="0"/>
		<xs:element name="XML-CONTENT" type="xmlblackbox:XML-CONTENT" minOccurs="0"/>
		<xs:element name="WEB-SERVICE-CLIENT" type="xmlblackbox:WEB-SERVICE-CLIENT" minOccurs="0"/>
		<xs:element name="SELENIUM" type="xmlblackbox:SELENIUM" minOccurs="0"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>
    
<xs:complexType name="DB-CONNECTION">
	<xs:annotation>
		<xs:documentation>
			Identify a database connection
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="CONNECTION" type="xmlblackbox:CONNECTION"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="CONNECTION">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="driver" type="xs:string" use="required"/>
	<xs:attribute name="db-url" type="xs:string" use="required"/>
	<xs:attribute name="username" type="xs:string" use="required"/>
	<xs:attribute name="password" type="xs:string" use="required"/>
</xs:complexType>

<xs:simpleType name="setVariableType">
	<xs:restriction base="xs:string">
		<xs:pattern value="XML_TYPE|VALUE_TYPE|DB_TYPE" />
	</xs:restriction>
</xs:simpleType>

<xs:complexType name="SET-VARIABLE">
	<xs:annotation>
		<xs:documentation>
			Identify a step for setting variable
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="SET" type="xmlblackbox:SET"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="SET">
	<xs:attribute name="connection" type="xs:string" use="required"/>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="value" type="xs:string" />
	<xs:attribute name="query" type="xs:string" />
	<xs:attribute name="filename" type="xs:string" />
	<xs:attribute name="namespace" type="xs:string" />
	<xs:attribute name="xpath" type="xs:string" />
	<xs:attribute name="type" type="xmlblackbox:setVariableType"/>
</xs:complexType>

<xs:complexType name="EXECUTE-QUERY">
	<xs:annotation>
		<xs:documentation>
			Identify a step for executing query
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="QUERY" type="xmlblackbox:QUERY"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="QUERY">
	<xs:attribute name="connection" type="xs:string" use="required"/>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="query" type="xs:string" use="required"/>
	<xs:attribute name="type" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="dataset">
	<xs:element type="xs:string"/>
</xs:complexType>

<xs:complexType name="CHECK-DB">
	<xs:annotation>
		<xs:documentation>
			Identify a step for db check
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="dataset" type="xmlblackbox:dataset"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="connection" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="RUN-PLUGIN">
	<xs:annotation>
		<xs:documentation>
			Identify a step for run a plugin
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="PARAMETERS" type="xmlblackbox:PARAMETERS"/>
	</xs:sequence>
	<xs:attribute name="class" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="PARAMETERS">
	<xs:sequence>
		<xs:element name="PARAMETER" type="xmlblackbox:PARAMETER"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="class" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="PARAMETER">
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="XML-CONTENT">
	<xs:annotation>
		<xs:documentation>
			Identify a step for checking xml file content
	</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="XML-INSERT-ROW" type="xmlblackbox:XML-ROW"/>
		<xs:element name="XML-CHECK-ROW" type="xmlblackbox:XML-ROW"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="fileinput" type="xs:string" use="required"/>
	<xs:attribute name="fileoutput" type="xs:string" use="optional"/>
	<xs:attribute name="namespace" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="XML-ROW">
	<xs:attribute name="NAME" type="xs:string" use="required"/>
	<xs:attribute name="xpath" type="xs:string" use="required"/>
	<xs:attribute name="value" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="WEB-SERVICE-CLIENT">
	<xs:annotation>
		<xs:documentation>
			Identify a step for executing a web service call
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="FILE-INPUT" type="xs:string"/>
		<xs:element name="FILE-OUTPUT" type="xs:string"/>
		<xs:element name="URL" type="xs:string"/>
		<xs:element name="STUB" type="xs:string"/>
		<xs:element name="OPERATION" type="xs:string"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="SELENIUM">
	<xs:annotation>
		<xs:documentation>
			Identify a step for executing a web navigation
		</xs:documentation>
	</xs:annotation>
	<xs:sequence>
		<xs:element name="FILE-NAVIGATION" type="xs:string"/>
		<xs:element name="PARAMETERS" type="xmlblackbox:PARAMETERS"/>
	</xs:sequence>
	<xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="VALIDATE-XML">
	<xs:annotation>
		<xs:documentation>
			Identify a step for validating an xml file
		</xs:documentation>
	</xs:annotation>
	<xs:attribute name="name" type="xs:string" use="required"/>
	<xs:attribute name="xml" type="xs:string" use="required"/>
	<xs:attribute name="xsd" type="xs:string" use="required"/>
</xs:complexType>

<xs:element name="TEST" type="xmlblackbox:TEST"/>


</xs:schema>

=== filippobosi/XmlBlackBox/functional-test/src/test/java/org/xmlblackbox/test/functional/examples/Example999WebApp.xml
<?xml version="1.0" encoding="utf-8" ?>
<TEST version="1.1" name="Example999" xmlns="http://www.xmlblackbox.org/xsd/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.xmlblackbox.org/xsd/src/test/resources/xmlblackbox_1_0.xsd">
   
	<!-- Connection initialize -->
    <DB-CONNECTIONS version="1.1">
        <CONNECTION name="DERBY" driver="org.apache.derby.jdbc.ClientDriver"
            db-url="jdbc:derby://localhost:1527/xmlblackbox;create=true"
            username="xmlblackbox" password="xmlblackbox"/>
    </DB-CONNECTIONS>

    <WAIT-TASK connection="DERBY" version="1.1" name="task">
    	<WAIT query="select * from pippo" timeout="10" />
    </WAIT-TASK>

    
    <!-- Example for creating an Xml file with modified value -->
    <XML-CONTENT name="xmlContent1" version="1.1" 
            fileinput="src/test/resources/templateXml/WebServiceTemplate/NewWebServiceTemplate.xml"
            fileoutput="target/Example999WebApp_1_out.xml"
            namespace="declare namespace xsd='http://webservice.test.xmlblackbox.org/';">
	        <XML-INSERT-ROW name="arg0"
                    xpath="$this//xsd:getPerson/xsd:arg0/xsd:address"
                    value="Via emilia"/>
	        <XML-INSERT-ROW name="arg1"
                    xpath="$this//xsd:getPerson/xsd:arg0/xsd:name"
                    value="Giulio"/>
	        <XML-INSERT-ROW name="arg2"
                    xpath="$this//xsd:getPerson/xsd:arg0/xsd:surname"
                    value="Bianchi"/>
	</XML-CONTENT>
	<!-- Example to verify values in xml file -->
    <XML-CONTENT version="1.1" name="XML-CONTENT Check"
            fileinput="target/Example999WebApp_1_out.xml"
            namespace="declare namespace xsd='http://webservice.test.xmlblackbox.org/';">
	        <XML-CHECK-ROW name="arg0"
                    xpath="$this//xsd:getPerson/xsd:arg0/xsd:address"
                    value="Via emilia"/>
	        <XML-CHECK-ROW name="arg1"
                    xpath="$this//xsd:getPerson/xsd:arg0/xsd:name"
                    value="Giulio"/>
	        <XML-CHECK-ROW name="arg2"
                    xpath="$this//xsd:getPerson/xsd:arg0/xsd:surname"
                    value="Bianchi"/>
    </XML-CONTENT>
	
	
    <WEB-SERVICE-CLIENT version="1.1" name="webservice">
        <FILE-INPUT>target/Example999WebApp_1_out.xml</FILE-INPUT>
        <FILE-OUTPUT>target/Example999WebApp_2_out.xml</FILE-OUTPUT>
        <URL>${EXAMPLE_WEB_SERVICE_URL@fileProperties}</URL>
        <STUB>org.xmlblackbox.test.webservice.client.NewWebServiceServiceStub</STUB>
        <OPERATION>getPerson</OPERATION>
    </WEB-SERVICE-CLIENT>		

    <VALIDATE-XML version="1.1" name="Validate"
        xml="target/Example999WebApp_2_out.xml"
        xsd="src/test/resources/wsdl/NewWebService.xsd" />

	<!-- Example to verify values in xml file -->
    <XML-CONTENT version="1.1" name="XML-CONTENT Check"
            fileinput="target/Example999WebApp_2_out.xml"
            namespace="declare namespace xsd='http://webservice.test.xmlblackbox.org/';">
	        <XML-CHECK-ROW name="arg0"
                    xpath="$this//xsd:getPersonResponse/return/address"
                    value="Via romaaaaaaaaaaaaaaaaaaaa"/>
	        <XML-CHECK-ROW name="arg1"
                    xpath="$this//xsd:getPersonResponse/return/name"
                    value="Mario"/>
	        <XML-CHECK-ROW name="arg2"
                    xpath="$this//xsd:getPersonResponse/return/surname"
                    value="Rossi"/>
    </XML-CONTENT>

    <SELENIUM version="1.1" name="Example999 navigazione con SELENIUM">
            <FILE-NAVIGATION>org.xmlblackbox.test.selenium.xmlblackbox.WebApplicationTest</FILE-NAVIGATION>
            <PARAMETERS>
                    <PARAMETER name="EXAMPLE_WEB_URL" value="${EXAMPLE_WEB_URL@fileProperties}" />
                    <PARAMETER name="username" value="${USERNAME_COMUNE@fileProperties}"/>
                    <PARAMETER name="password" value="${PASSWORD_COMUNE@fileProperties}"/>
            </PARAMETERS>
    </SELENIUM>

</TEST>
